name: collogefinalpoject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  http: ^1.3.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  fl_chart: ^0.65.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Untitled_design20212.png"
  adaptive_icon_background: "#ffffff" # أو صورة خلفية إن أردت
  adaptive_icon_foreground: "assets/Untitled_design20212.png"
  remove_alpha_ios: true # لتجنب مشاكل الشفافية في iOS

flutter:
  uses-material-design: true
  assets:
    - assets/
